#!/bin/bash
##c get chrome history to text
sqlite3 "/mnt/c/Users/jayst/AppData/Local/Google/Chrome/User Data/Default/History" ".output history.txt" "SELECT datetime(last_visit_time/1000000-11644473600, 'unixepoch') as last_visited, url, title, visit_count FROM urls order by last_visited;"  ".exit"
