#!/bin/bash
##c list recent file changes to projects/left.txt
#todo mv left to better dir?
shopt -s expand_aliases
source ~/.bash_aliases
rm /mnt/c/projects/recent.txt || echo "no recent"
#https://unix.stackexchange.com/questions/1496/why-doesnt-my-bash-script-recognize-aliases
if [ -e $HOME/.bash_aliases ]; then
  source $HOME/.bash_aliases
fi
if [ $# -eq 0 ]; then
  printf '%s\n' "running recent from ~/script"
  day=2
  cd /mnt/c/projects/
  fdm -tf --changed-within="$day"days | xargs ls -lhrt | awk '{ print $9 " " $6 " " $7 " " $8}' | tac | sort >/mnt/c/projects/myr/left.txt
  cd -
else
  me=$1
  fdm --changed-within="$me"days | xargs ls -lhrt | awk '{ print $9 " " $6 " " $7 " " $8}' | tac | sort >/mnt/c/projects/myr/left.txt
fi
#call py order left
/mnt/c/projects/myr/lsort.py
