#!/bin/bash
##c !good https://www.theunixschool.com/2011/08/shell-script-to-do-shell-scripting.html
if [ ! -f "$1" ]; then
  echo "#!/usr/bin/bash" > "$1"
fi

while  true ;
do
        nvim "$1"
        chmod 755 "$1"
        ./"$1"
        read dummy
done
