#!/bin/bash
##c utility to download list sound youtube  videos
clear
echo "Youtube audio downloader"
echo "-----------------------------"
cd /mnt/c/you || exit
fd . -td -d 1 | column | nl
cd - || exit
read -p 'Enter DL youtube directory: ' DIRY
# DIRY="lazy"
newdir="/mnt/c/you/$DIRY"
echo "$newdir"
mkdir -p "$newdir"
cd "$newdir" || exit
read -p  'Enter DL youtube audio: ' USERVAR
echo "USERVAR IS: ${USERVAR}"
#read -p 'enter name: ' ANAME
yt-dlp -f 'ba' --embed-metadata -x --audio-format mp3 "$USERVAR" -o '%(title)s.mp3' > /dev/null 2>&1 
#yt-dlp -f 'ba' --embed-metadata -x --audio-format mp3 "$USERVAR" -o "$ANAME.mp3"
name=$(yt-dlp --get-filename -o "%(title)s.%(ext)s" "$USERVAR" | sed 's/webm/mp3/')
echo "$(date)" '- mp3 ' "$name" ' - ' "$USERVAR" "$newdir" >>/mnt/c/you/dates.txt
touch "$ANAME.mp3"
#>output.log 2>&1 &
echo "runing space"
/home/steff007/script/space
echo "done with $COMP"
